import re

from pyodbc import Row


class Manufacturer:
    def __init__(self, name: str, pattern: str | None = None) -> None:
        self.name = name
        if pattern is None:
            pattern = f"^{self.name}"
        self.pattern = pattern


def get_inventory_row(mfg: Manufacturer, row: Row) -> tuple[str, str, int]:
    return f'\'{re.sub(mfg.pattern, "", row[0])}', mfg.name.upper(), int(row[2])


AUTHORIZED_MFGS = [
    Manufacturer("CIT", r"^CIT "),
    Manufacturer("ARIES", r"^ARIES "),
    Manufacturer("ALTECH", r"^ALTECH "),
    Manufacturer("BUSSMANN", r"BUSSMANN? "),
    Manufacturer("AAVID", r"^AAVID "),
    Manufacturer("AEH", r"^AEH "),
    Manufacturer("AKRO-MILS", r"^AKRO-MILS "),
    Manufacturer("ALL-STATES", r"^ALL-STATES "),
    Manufacturer("ALPHA", r"^ALPHA "),
    Manufacturer("KOSOO", r"^KOSOO "),
    Manufacturer("KINGTRONICS", r"^KT "),
    Manufacturer("KWLE", r"^KWLE "),
    Manufacturer("LEDTRONICS", r"^LEDTRONICS "),
    Manufacturer("LEM", r"^LEM "),
    Manufacturer("LEOCO", r"^LEOCO "),
    Manufacturer("LEVITON", r"^LEVITON "),
    Manufacturer("LITTELFUSE", r"^LITTELFUSE "),
    Manufacturer("LMB", r"^LMB "),
    Manufacturer("MACROMATIC", r"^MACROMATIC "),
    Manufacturer("SCI", r"^SCI "),
    Manufacturer("SELECTA", r"^SELECTA "),
    Manufacturer("SELTERM", r"^SELTERM "),
    Manufacturer("SEMITRONICS", r"^SEMITRONICS "),
    Manufacturer("SERPAC", r"^SERPAC "),
    Manufacturer("AND", r"^AND "),
    Manufacturer("AOP", r"^AOP "),
    Manufacturer("APLHA", r"^APLHA "),
    Manufacturer("APM", r"^APM "),
    Manufacturer("APTIV", r"^APTIV "),
    Manufacturer("ASC", r"^ASC "),
    Manufacturer("ASI", r"^ASI "),
    Manufacturer("ASJ", r"^ASJ "),
    Manufacturer("ATLAS", r"^ATLAS "),
    Manufacturer("AZMEX", r"^AZMEX "),
    Manufacturer("BEAU", r"^BEAU "),
    Manufacturer("BEISIT", r"^BEISIT "),
    Manufacturer("BLOCKMASTER", r"^BLOCKMASTER "),
    Manufacturer("BONDHUS", r"^BONDHUS "),
    Manufacturer("BOURNS", r"^BOURNS "),
    Manufacturer("BURNDY", r"^BURNDY "),
    Manufacturer("CAL-CHIP", r"^CAL-CHIP "),
    Manufacturer("CATAMOUNT", r"^CATAMOUNT "),
    Manufacturer("CDIL", r"^CDIL "),
    Manufacturer("CINETECH", r"^CINETECH "),
    Manufacturer("CKE", r"^CKE "),
    Manufacturer("CLEC", r"^CLEC "),
    Manufacturer("CONSOLIDATE", r"^CONSOLIDATE "),
    Manufacturer("CONTA CLIP", r"^CONTA CLIP "),
    Manufacturer("COOLTRON", r"^COOLTRON "),
    Manufacturer("CRANE", r"^CRANE "),
    Manufacturer("DAVIES", r"^DAVIES "),
    Manufacturer("DDK", r"^DDK "),
    Manufacturer("DEGSON", r"^DEGSON "),
    Manufacturer("DEKA", r"^DEKA "),
    Manufacturer("DELTROL", r"^DELTROL "),
    Manufacturer("DUNBAR", r"^DUNBAR "),
    Manufacturer("E-Z SWITCH", r"^E-Z SWITCH "),
    Manufacturer("ECCO", r"^ECCO "),
    Manufacturer("ECE", r"^ECE "),
    Manufacturer("ECLIPSE", r"^ECLIPSE "),
    Manufacturer("ECS", r"^ECS "),
    Manufacturer("EIC", r"^EIC "),
    Manufacturer("ELCO", r"^ELCO "),
    Manufacturer("ETC", r"^ETC "),
    Manufacturer("FALCON WIRE", r"^FALCON "),
    Manufacturer("FASCOMP", r"^FASCOMP "),
    Manufacturer("FEMA", r"^FEMA "),
    Manufacturer("FTZ", r"^FTZ "),
    Manufacturer("GC WALDOM", r"^(GC|G\.C\.) "),
    Manufacturer("GC WALDOM", r"^GC "),
    Manufacturer("HAMMOND", r"^HAMMOND "),
    Manufacturer("HASCO", r"^HASCO "),
    Manufacturer("HELLA", r"^HELLA "),
    Manufacturer("HELLERMANN TYTON", r"^HELLERMANN TYTON "),
    Manufacturer("HOLLINGSWORTH", r"^HOLLINGSWORTH "),
    Manufacturer("HOPKINS", r"^HOPKINS "),
    Manufacturer("HUWU", r"^HUWU "),
    Manufacturer("IDEAL", r"^IDEAL "),
    Manufacturer("INPOWER", r"^INPOWER "),
    Manufacturer("INSULTAB", r"^INSULTAB "),
    Manufacturer("ISOCOM", r"^ISOCOM "),
    Manufacturer("IXYS", r"^IXYS "),
    Manufacturer("JB", r"^JB "),
    Manufacturer("JKL", r"^JKL "),
    Manufacturer("JUDCO", r"^JUDCO "),
    Manufacturer("KANEBRIDGE", r"^KANEBRIDGE "),
    Manufacturer("KEYSTONE", r"^KEYSTONE "),
    Manufacturer("MALLORY", r"^MALLORY "),
    Manufacturer("MAN/CDT", r"^MAN/CDT "),
    Manufacturer("MANHATTAN", r"^MANHATTAN "),
    Manufacturer("MARCO", r"^MARCO "),
    Manufacturer("MEI", r"^MEI "),
    Manufacturer("MEMCOR", r"^MEMCOR "),
    Manufacturer("MERITEK", r"^MERITEK "),
    Manufacturer("MICROCHIP", r"^MICROCHIP "),
    Manufacturer("MIYAGAWA", r"^MIYAGAWA "),
    Manufacturer("MODE", r"^MODE "),
    Manufacturer("MOLEX", r"^MOLEX "),
    Manufacturer("MORRIS", r"^MORRIS "),
    Manufacturer("MOSPEC", r"^MOSPEC "),
    Manufacturer("MUELLER", r"^MUELLER "),
    Manufacturer("NICHIFU", r"^NICHIFU "),
    Manufacturer("NJS", r"^NJS "),
    Manufacturer("NKL", r"^NKL "),
    Manufacturer("NTE", r"^NTE "),
    Manufacturer("OPTIFUSE", r"^OPTIFUSE "),
    Manufacturer("OST", r"^OST "),
    Manufacturer("PANDUIT", r"^PANDUIT "),
    Manufacturer("PEC", r"^PEC "),
    Manufacturer("PFLITSCH", r"^PFLITSCH "),
    Manufacturer("PHILMORE", r"^PHILMORE "),
    Manufacturer("PICKER", r"^PICKER "),
    Manufacturer("POLLAK", r"^POLLAK "),
    Manufacturer("PRP", r"^PRP "),
    Manufacturer("RAYEX", r"^RAYEX "),
    Manufacturer("RENCO", r"^RENCO "),
    Manufacturer("RIEDON", r"^RIEDON "),
    Manufacturer("ROADPRO", r"^ROADPRO "),
    Manufacturer("SALECOM", r"^SALECOM "),
    Manufacturer("SAMWHA", r"^SAMWHA "),
    Manufacturer("SANDAN", r"^SANDAN "),
    Manufacturer("SOLICO", r"^SOLICO "),
    Manufacturer("STACO", r"^STACO "),
    Manufacturer("STANCOR", r"^STANCOR "),
    Manufacturer("SUNS", r"^SUNS "),
    Manufacturer("T&B", r"^T&B "),
    Manufacturer("TCI", r"^TCI "),
    Manufacturer("TOCOS", r"^TOCOS "),
    Manufacturer("TROMBETTA", r"^TROMBETTA "),
    Manufacturer("WURTH", r"^WURTH "),
    Manufacturer("WTE", r"^WTE "),
]

NON_AUTHORIZED_MFGS = [
    Manufacturer("3M", r"^3M "),
    Manufacturer("ABB", r"^ABB "),
    Manufacturer("ABBOTT", r"^ABBOTT "),
    Manufacturer("ABRACON", r"^ABRACON "),
    Manufacturer("ABS", r"^ABS "),
    Manufacturer("AC DELCO", r"^AC DELCO "),
    Manufacturer("ACCUMETRIC", r"^ACCUMETRIC "),
    Manufacturer("ACCURATE", r"^ACCURATE "),
    Manufacturer("ACP", r"^ACP "),
    Manufacturer("ACT", r"^ACT "),
    Manufacturer("ACTRON", r"^ACTRON "),
    Manufacturer("ADC", r"^ADC "),
    Manufacturer("AE", r"^AE "),
    Manufacturer("AEG", r"^AEG "),
    Manufacturer("AEROSPACE", r"^AEROSPACE "),
    Manufacturer("AEROVOX", r"^AEROVOX "),
    Manufacturer("AFC AFC121", r"^AFC121 "),
    Manufacturer("AGASTAT", r"^AGASTAT "),
    Manufacturer("AGILENT", r"^AGILENT "),
    Manufacturer("AIM", r"^AIM "),
    Manufacturer("AIRCO", r"^AIRCO "),
    Manufacturer("ALBRIGHT", r"^ALBRIGHT "),
    Manufacturer("ALCO", r"^ALCO "),
    Manufacturer("ALCOA", r"^ALCOA "),
    Manufacturer("ALLEGRO", r"^ALLEGRO "),
    Manufacturer("ALLEN BRADLEY", r"^ALLEN BRADLEY "),
    Manufacturer("ALTERA", r"^ALTERA "),
    Manufacturer("AMERICORD", r"^AM CORD "),
    Manufacturer("AMD", r"^AMD "),
    Manufacturer("AME", r"^AME "),
    Manufacturer("AMERICAN BEAUTY", r"^AMER BEAUTY "),
    Manufacturer("AMI", r"^AMI "),
    Manufacturer("AML", r"^AML "),
    Manufacturer("AMP", r"^AMP "),
    Manufacturer("AMPHENOL", r"^AMPHENOL "),
    Manufacturer("AMPS", r"^AMPS "),
    Manufacturer("AMSOIL", r"^AMSOIL "),
    Manufacturer("ANALOG DEVICES", r"^ANALOG DEVICES "),
    Manufacturer("ANDERSON", r"^ANDERSON "),
    Manufacturer("APD", r"^APD "),
    Manufacturer("API", r"^API "),
    Manufacturer("APLUS", r"^APLUS "),
    Manufacturer("APP", r"^APP "),
    Manufacturer("ARCO", r"^ARCO "),
    Manufacturer("ARIES", r"^ARIES "),
    Manufacturer("ARLON", r"^ARLON "),
    Manufacturer("AROMAT", r"^AROMAT "),
    Manufacturer("ARROW HART", r"^ARROW HART "),
    Manufacturer("ASP", r"^ASP "),
    Manufacturer("ASSMANN", r"^ASSMANN "),
    Manufacturer("ATLANTIC", r"^ATLANTIC "),
    Manufacturer("ATMEL", r"^ATMEL "),
    Manufacturer("AUDIO PIPE", r"^AUDIO PIPE "),
    Manufacturer("AVAGO", r"^AVAGO "),
    Manufacturer("AVERY", r"^AVERY "),
    Manufacturer("AVG", r"^AVG "),
    Manufacturer("AVX", r"^AVX "),
    Manufacturer("ALLIED WIRE", r"^AW "),
    Manufacturer("ALLIED WIRE", r"^AWC "),
    Manufacturer("AXICOM", r"^AXICOM "),
    Manufacturer("B-LINE", r"^B-LINE "),
    Manufacturer("BACKSHELL", r"^BACKSHELL "),
    Manufacturer("BADGER", r"^BADGER "),
    Manufacturer("BALDWIN", r"^BALDWIN "),
    Manufacturer("BARON", r"^BARON "),
    Manufacturer("BEC", r"^BEC "),
    Manufacturer("BECKMAN", r"^BECKMAN "),
    Manufacturer("BEI", r"^BEI "),
    Manufacturer("BELDEN", r"^BELDEN "),
    Manufacturer("BENDIX", r"^BENDIX "),
    Manufacturer("BENNER NAWMAN", r"^BENNER NAWMAN "),
    Manufacturer("BERG", r"^BERG "),
    Manufacturer("BERGQUIST", r"^BERGQUIST "),
    Manufacturer("BI TECH", r"^BI TECH "),
    Manufacturer("BISHOP", r"^BISHOP "),
    Manufacturer("BIVAR", r"^BIVAR "),
    Manufacturer("BLOCKMASTER", r"^BLOCKMASTER "),
    Manufacturer("BLUE SEA", r"^BLUE SEA "),
    Manufacturer("BOMAR", r"^BOMAR "),
    Manufacturer("BONDHUS", r"^BONDHUS "),
    Manufacturer("BOPLA", r"^BOPLA "),
    Manufacturer("BOSCH", r"^BOSCH "),
    Manufacturer("BOURNS", r"^BOURNS "),
    Manufacturer("BOW", r"^BOW "),
    Manufacturer("BREMEN", r"^BREMEN "),
    Manufacturer("BRIDGEPORT", r"^BRIDGEPORT "),
    Manufacturer("BRIGHT STAR", r"^BRIGHT STAR "),
    Manufacturer("BROWN BOVERI", r"^BROWN BOVERI "),
    Manufacturer("BRUNSWICK", r"^BRUNSWICK "),
    Manufacturer("BUCHANAN", r"^BUCHANAN "),
    Manufacturer("BUD", r"^BUD "),
    Manufacturer("BULGIN", r"^BULGIN "),
    Manufacturer("BURGESS", r"^BURGESS "),
    Manufacturer("BURR BROWN", r"^BURR BROWN "),
    Manufacturer("BWC", r"^BWC "),
    Manufacturer("CALOGIC", r"^CALOGIC "),
    Manufacturer("CALRAD", r"^CALRAD "),
    Manufacturer("CANAL", r"^CANAL "),
    Manufacturer("CANFIELD", r"^CANFIELD "),
    Manufacturer("CANNON", r"^CANNON "),
    Manufacturer("CAPAR", r"^CAPAR "),
    Manufacturer("CAPTEK", r"^CAPTEK "),
    Manufacturer("CARLING SWITCH", r"^CARLING "),
    Manufacturer("CAROL", r"^CAROL "),
    Manufacturer("CASCO", r"^CASCO "),
    Manufacturer("CATAMOUNT", r"^CATAMOUNT "),
    Manufacturer("CCE", r"^CCE "),
    Manufacturer("CCSE", r"^CCSE "),
    Manufacturer("CCSR", r"^CCSR "),
    Manufacturer("CDC", r"^CDC "),
    Manufacturer("CDE", r"^CDE "),
    Manufacturer("CDIL", r"^CDIL "),
    Manufacturer("CE", r"^CE (?!ELEC)"),
    Manufacturer("CEC", r"^CEC "),
    Manufacturer("CEI", r"^CEI "),
    Manufacturer("CEL", r"^CEL "),
    Manufacturer("CENTRAL TECH", r"^CENTRAL TECH "),
    Manufacturer("CENTRALAB", r"^CENTRALAB "),
    Manufacturer("CERRO", r"^CERRO "),
    Manufacturer("CES", r"^CES "),
    Manufacturer("CF THOMPSON", r"^CF THOMPSON "),
    Manufacturer("CGW", r"^CGW "),
    Manufacturer("CHASE-SHAWMUT", r"^CHASE-SHAWMUT "),
    Manufacturer("CHEMTRONICS", r"^CHEMTRONICS "),
    Manufacturer("CHEQUERS", r"^CHEQUERS "),
    Manufacturer("CHERRY", r"^CHERRY "),
    Manufacturer("CHS", r"^CHS "),
    Manufacturer("CI", r"^CI "),
    Manufacturer("CINCH", r"^CINCH "),
    Manufacturer("CIRCLE F", r"^CIRCLE F "),
    Manufacturer("CLAIREX", r"^CLAIREX "),
    Manufacturer("CLARE", r"^CLARE "),
    Manufacturer("CLAROSTAT", r"^CLAROSTAT "),
    Manufacturer("CLE", r"^CLE "),
    Manufacturer("CMC", r"^CMC "),
    Manufacturer("CML", r"^CML "),
    Manufacturer("CNLINKO", r"^CNLINKO "),
    Manufacturer("COBRA", r"^COBRA "),
    Manufacturer("CODAC", r"^CODAC "),
    Manufacturer("COILCRAFT", r"^COILCRAFT "),
    Manufacturer("COLE HERSEE", r"^COLE HERSEE "),
    Manufacturer("COLEFLEX", r"^COLEFLEX "),
    Manufacturer("COLEMAN", r"^COLEMAN "),
    Manufacturer("COLUMBIA", r"^COLUMBIA "),
    Manufacturer("COMM CON", r"^COMM CON "),
    Manufacturer("COMPONENTS CORP", r"^COMP CORP "),
    Manufacturer("CONCORD", r"^CONCORD "),
    Manufacturer("CONNECTOR", r"^CONNECTOR "),
    Manufacturer("CONXALL", r"^CONXALL "),
    Manufacturer("COPPERFIELD", r"^COPPERFIELD "),
    Manufacturer("CORCOM", r"^CORCOM "),
    Manufacturer("CORNING", r"^CORNING "),
    Manufacturer("CORROSEAL", r"^CORROSEAL "),
    Manufacturer("CORROSIONX", r"^CORROSIONX "),
    Manufacturer("COSMO", r"^COSMO "),
    Manufacturer("CPE", r"^CPE "),
    Manufacturer("CRL", r"^CRL "),
    Manufacturer("CROSS-LINK", r"^CROSS-LINK "),
    Manufacturer("CROUSE-HINDS", r"^CROUSE-HINDS "),
    Manufacturer("CRYDOM", r"^CRYDOM "),
    Manufacturer("CSC", r"^CSC "),
    Manufacturer("CTEK", r"^CTEK "),
    Manufacturer("CTI", r"^CTI "),
    Manufacturer("CTP", r"^CTP "),
    Manufacturer("CTS", r"^CTS "),
    Manufacturer("CUI", r"^CUI "),
    Manufacturer("CURTIS", r"^CURTIS "),
    Manufacturer("CUSTOM CONNECTOR", r"^CUSTOM CONNECTOR "),
    Manufacturer("CW INDUSTRIES", r"^CW IND "),
    Manufacturer("CW INDUSTRIES", r"^CWI "),
    Manufacturer("CYG", r"^CYG "),
    Manufacturer("CYI", r"^CYI "),
    Manufacturer("CZ LABS", r"^CZ LABS "),
    Manufacturer("D-AGE", r"^D-AGE "),
    Manufacturer("DABURN", r"^DABURN "),
    Manufacturer("DAIER", r"^DAIER "),
    Manufacturer("DALE", r"^DALE "),
    Manufacturer("DALLAS", r"^DALLAS "),
    Manufacturer("DEARBORN", r"^DEARBORN "),
    Manufacturer("DEI", r"^DEI "),
    Manufacturer("DEL CITY", r"^DEL CITY "),
    Manufacturer("DELFINGEN", r"^DELFINGEN "),
    Manufacturer("DELTA", r"^DELTA "),
    Manufacturer("DETCO", r"^DETCO "),
    Manufacturer("DEUTSCH", r"^DEUTSCH "),
    Manufacturer("DIALIGHT", r"^DIALIGHT "),
    Manufacturer("DICKSON", r"^DICKSON "),
    Manufacturer("DICOR", r"^DICOR "),
    Manufacturer("DII", r"^DII "),
    Manufacturer("DIMCO GRAY", r"^DIMCO GRAY "),
    Manufacturer("DINKLE", r"^DINKLE "),
    Manufacturer("DIODE", r"^DIODE "),
    Manufacturer("DIODES INC", r"^DIODES INC "),
    Manufacturer("DIXIE", r"^DIXIE "),
    Manufacturer("DJK", r"^DJK "),
    Manufacturer("DMC", r"^DMC "),
    Manufacturer("DONG YANG", r"^DONG YANG "),
    Manufacturer("DRAKE", r"^DRAKE "),
    Manufacturer("DROSSBACH", r"^DROSSBACH "),
    Manufacturer("DRYCONN", r"^DRYCONN "),
    Manufacturer("DSI", r"^DSI "),
    Manufacturer("DURACELL", r"^DURACELL "),
    Manufacturer("DURHAM", r"^DURHAM "),
    Manufacturer("DYNAPAR", r"^DYNAPAR "),
    Manufacturer("DYNATEX", r"^DYNATEX "),
    Manufacturer("E-SWITCH", r"^E-SWITCH "),
    Manufacturer("EAGLE", r"^EAGLE (?!CONNECTOR)"),
    Manufacturer("EAST PENN", r"^EAST PENN "),
    Manufacturer("EASY WIK", r"^EASY WIK "),
    Manufacturer("EATON", r"^EATON "),
    Manufacturer("EBG", r"^EBG "),
    Manufacturer("ECS", r"^ECS[ -]"),
    Manufacturer("EBM-PAPST", r"^EBM-PAPST "),
    Manufacturer("EDI", r"^EDI "),
    Manufacturer("EDWARDS", r"^EDWARDS "),
    Manufacturer("EF BATTERY", r"^EF BATTERY "),
    Manufacturer("EG&G", r"^EG&G "),
    Manufacturer("EHC", r"^EHC "),
    Manufacturer("ELCAP", r"^ELCAP "),
    Manufacturer("ELCO", r"^ELCO "),
    Manufacturer("ELECTRO ADAPTOR", r"^ELECTRO ADAPTER "),
    Manufacturer("ELECTRO-MATIC", r"^ELECTRO-MATIC "),
    Manufacturer("ELECTROCUBE", r"^ELECTROCUBE "),
    Manufacturer("ELECTROLINE", r"^ELECTROLINE "),
    Manufacturer("ELECTRONIC TRANSISTORS", r"^ELECTRONIC TRANSISTORS "),
    Manufacturer("ELEKTRALINK", r"^ELEKTRALINK "),
    Manufacturer("ELNA", r"^ELNA "),
    Manufacturer("EMC", r"^EMC "),
    Manufacturer("EMM", r"^EMM "),
    Manufacturer("ENCORE", r"^ENCORE "),
    Manufacturer("ENDRIES", r"^ENDRIES "),
    Manufacturer("ENERGIZER", r"^ENERGIZER "),
    Manufacturer("EPCOS", r"^EPCOS "),
    Manufacturer("EPE", r"^EPE "),
    Manufacturer("EPSON", r"^EPSON "),
    Manufacturer("ERI", r"^ERI "),
    Manufacturer("ESC", r"^ESC "),
    Manufacturer("ESP", r"^ESP "),
    Manufacturer("ESSEX", r"^ESSEX "),
    Manufacturer("ETA", r"^ETA "),
    Manufacturer("ETCO", r"^ETCO "),
    Manufacturer("ETS", r"^ETS "),
    Manufacturer("EUBANKS", r"^EUBANKS "),
    Manufacturer("EVEREADY", r"^EVEREADY "),
    Manufacturer("EVERLIGHT", r"^EVERLIGHT "),
    Manufacturer("EVOX/RIFA", r"^EVOX/RIFA "),
    Manufacturer("EXAR", r"^EXAR "),
    Manufacturer("EXCELENE", r"^EXCELENE "),
    Manufacturer("FAGOR", r"^FAGOR "),
    Manufacturer("FAIR-RITE", r"^FAIR-RITE "),
    Manufacturer("FAIRCHILD", r"^FAIRCHILD "),
    Manufacturer("FAIRCHILD", r"^FAIRCHLD "),
    Manufacturer("FAIRCHILD", r"^FAIRCHULD "),
    Manufacturer("FARGO", r"^FARGO "),
    Manufacturer("FCI", r"^FCI "),
    Manufacturer("FE", r"^FE "),
    Manufacturer("FENWAL", r"^FENWAL "),
    Manufacturer("FIAMM", r"^FIAMM "),
    Manufacturer("FIRSTOHM", r"^FIRSTOHM "),
    Manufacturer("FLAMBEAU", r"^FLAMBEAU "),
    Manufacturer("FLEX WIRES", r"^FLEX WIRES "),
    Manufacturer("FLOYD BELL", r"^FLOYD BELL "),
    Manufacturer("FLUKE", r"^FLUKE "),
    Manufacturer("FORSBERG", r"^FORSBERG "),
    Manufacturer("FOUR SEASONS", r"^FOUR SEASONS "),
    Manufacturer("FREESCALE", r"^FREESCALE "),
    Manufacturer("FSC", r"^FSC "),
    Manufacturer("FTDI", r"^FTDI "),
    Manufacturer("FUAN", r"^FUAN "),
    Manufacturer("FUJISOKU", r"^FUJISOKU "),
    Manufacturer("FUJITSU", r"^FUJITSU "),
    Manufacturer("GARDINER", r"^GARDINER "),
    Manufacturer("GARDNER", r"^GARDNER "),
    Manufacturer("GARDTEC", r"^GARDTEC "),
    Manufacturer("GATES", r"^GATES "),
    Manufacturer("GBE", r"^GBE "),
    Manufacturer("GCC", r"^GCC "),
    Manufacturer("GE", r"^GE "),
    Manufacturer("GENERAL TRANSISTOR", r"^GENERAL TRANSISTOR "),
    Manufacturer("GEP", r"^GEP "),
    Manufacturer("GERBER", r"^GERBER "),
    Manufacturer("GERMANIUM", r"^GERMANIUM "),
    Manufacturer("GI", r"^GI "),
    Manufacturer("GLENAIR", r"^GLENAIR "),
    Manufacturer("GLO OHM", r"^GLO OHM "),
    Manufacturer("GLOBAL", r"^GLOBAL "),
    Manufacturer("GLOBE LAMP", r"^GLOBE LAMP "),
    Manufacturer("GLOWLITE", r"^GLOWLITE "),
    Manufacturer("GML", r"^GML "),
    Manufacturer("GOLDEN POWER", r"^GOLDEN POWER "),
    Manufacturer("GOLDHILL", r"^GOLDHILL "),
    Manufacturer("GOLDSTAR", r"^GOLDSTAR "),
    Manufacturer("GOULD", r"^GOULD "),
    Manufacturer("GOULD-SHAWMUT", r"^GOULD-SHAWMUT "),
    Manufacturer("GRAYHILL", r"^GRAYHILL "),
    Manufacturer("GREAVES", r"^GREAVES "),
    Manufacturer("GREENLITE", r"^GREENLITE "),
    Manufacturer("GRIGSBY-BARTON", r"^GRIGSBY-BARTON "),
    Manufacturer("GROTE", r"^GROTE "),
    Manufacturer("GS", r"^GS "),
    Manufacturer("GSI", r"^GSI "),
    Manufacturer("GWE", r"^GWE "),
    Manufacturer("H.A.KING", r"^H.A.KING "),
    Manufacturer("HALCO", r"^HALCO "),
    Manufacturer("HAMAMATSU", r"^HAMAMATSU "),
    Manufacturer("HAMLIN", r"^HAMLIN "),
    Manufacturer("HARBOUR", r"^HARBOUR "),
    Manufacturer("HARMAN", r"^HARMAN "),
    Manufacturer("HARRIS", r"^HARRIS "),
    Manufacturer("HARTING", r"^HARTING "),
    Manufacturer("HC", r"^HC "),
    Manufacturer("HDT", r"^HDT "),
    Manufacturer("HE", r"^HE "),
    Manufacturer("HEI", r"^HEI "),
    Manufacturer("HEINEMANN", r"^HEINEMANN "),
    Manufacturer("HERMETIC", r"^HERMETIC "),
    Manufacturer("HEYCO", r"^HEYCO "),
    Manufacturer("ABBATRON", r"^HHS "),
    Manufacturer("HI SINCERITY", r"^HI SINCERITY "),
    Manufacturer("HI-TEC", r"^HI-TEC "),
    Manufacturer("HIKARI", r"^HIKARI "),
    Manufacturer("HILEC", r"^HILEC "),
    Manufacturer("HILTON", r"^HILTON "),
    Manufacturer("HIQ", r"^HIQ "),
    Manufacturer("HIROSE", r"^HIROSE "),
    Manufacturer("HITACHI", r"^HITACHI "),
    Manufacturer("HITANO", r"^HITANO "),
    Manufacturer("HM DIGITAL", r"^HM DIGITAL "),
    Manufacturer("HMT", r"^HMT "),
    Manufacturer("HO CHIEN", r"^HO CHIEN "),
    Manufacturer("HOFFMAN", r"^HOFFMAN "),
    Manufacturer("HOLMBERG", r"^HOLMBERG "),
    Manufacturer("HOMAK", r"^HOMAK "),
    Manufacturer("HONEYWELL", r"^HONEYWELL "),
    Manufacturer("HOOSIER", r"^HOOSIER "),
    Manufacturer("HP", r"^HP "),
    Manufacturer("HPN", r"^HPN "),
    Manufacturer("HTP", r"^HTP "),
    Manufacturer("HTS", r"^HTS "),
    Manufacturer("HUBBELL", r"^HUBBELL "),
    Manufacturer("HUIPU", r"^HUIPU "),
    Manufacturer("HUTSON", r"^HUTSON "),
    Manufacturer("HYE", r"^HYE "),
    Manufacturer("HYMEG", r"^HYMEG "),
    Manufacturer("HYSON", r"^HYSON "),
    Manufacturer("ICC", r"^ICC "),
    Manufacturer("ICT", r"^ICT "),
    Manufacturer("ID", r"^ID "),
    Manufacturer("IDEC", r"^IDEC "),
    Manufacturer("IDI", r"^IDI "),
    Manufacturer("IDT", r"^IDT "),
    Manufacturer("IE", r"^IE "),
    Manufacturer("IERC", r"^IERC "),
    Manufacturer("ILLINOIS CAP", r"^ILL INOIS CAP "),
    Manufacturer("ILLINOIS CAP", r"^ILLINOIS CAP "),
    Manufacturer("ILSCO", r"^ILSCO "),
    Manufacturer("IMLEC", r"^IMLEC "),
    Manufacturer("IND/MIDWEC", r"^IND/MIDWEC "),
    Manufacturer("INDIANA TRANS", r"^INDIANA TRANS "),
    Manufacturer("INFINEON", r"^INFINEON "),
    Manufacturer("INFINEON", r"^INFINEON/IR "),
    Manufacturer("INT WIRE", r"^INT WIRE "),
    Manufacturer("INTEL", r"^INTEL "),
    Manufacturer("INTERMATIC", r"^INTERMATIC "),
    Manufacturer("INTERNATIONAL DEVICES", r"^INTERNATIONAL DEVICES "),
    Manufacturer("INTERSIL", r"^INTERSIL "),
    Manufacturer("INTERSTATE", r"^INTERSTATE "),
    Manufacturer("IR", r"^IR "),
    Manufacturer("IRC", r"^IRC "),
    Manufacturer("ISD", r"^ISD "),
    Manufacturer("ISI", r"^ISI "),
    Manufacturer("ISKRA", r"^ISKRA "),
    Manufacturer("ITT", r"^ITT "),
    Manufacturer("ITW", r"^ITW "),
    Manufacturer("IWC", r"^IWC "),
    Manufacturer("IZTOSS", r"^IZTOSS "),
    Manufacturer("J&I", r"^J&I "),
    Manufacturer("JAICO", r"^JAICO "),
    Manufacturer("JAMICON", r"^JAMICON "),
    Manufacturer("JC", r"^JC "),
    Manufacturer("JEMCO", r"^JEMCO "),
    Manufacturer("JOYIN", r"^JOYIN "),
    Manufacturer("JRC", r"^JRC "),
    Manufacturer("JS", r"^JS "),
    Manufacturer("JSC", r"^JSC "),
    Manufacturer("JST", r"^JST "),
    Manufacturer("KCK", r"^KCK "),
    Manufacturer("KEC", r"^KEC "),
    Manufacturer("KEL-AM", r"^KEL-AM "),
    Manufacturer("KEMET", r"^KEMET "),
    Manufacturer("KEMTROK", r"^KEMTROK "),
    Manufacturer("KEN OHM", r"^KEN OHM "),
    Manufacturer("KESTER", r"^KESTER "),
    Manufacturer("KINGBRIGHT", r"^KINGBRIGHT "),
    Manufacturer("KINGS", r"^KINGS "),
    Manufacturer("KK", r"^KK "),
    Manufacturer("KLEIN", r"^KLEIN "),
    Manufacturer("KLIXON", r"^KLIXON "),
    Manufacturer("KOA", r"^KOA "),
    Manufacturer("KOBICONN", r"^KOBICONN "),
    Manufacturer("KRYLON", r"^KRYLON "),
    Manufacturer("KULKA", r"^KULKA "),
    Manufacturer("LAIRD", r"^LAIRD "),
    Manufacturer("LAMB", r"^LAMB "),
    Manufacturer("LAPP", r"^LAPP "),
    Manufacturer("LARIBEE", r"^LARIBEE "),
    Manufacturer("LC", r"^LC "),
    Manufacturer("LEAR", r"^LEAR "),
    Manufacturer("LED SOLUTIONS", r"^LED SOLUTIONS "),
    Manufacturer("LEECRAFT", r"^LEECRAFT "),
    Manufacturer("LEGRAND", r"^LEGRAND "),
    Manufacturer("LEICK", r"^LEICK "),
    Manufacturer("LELON", r"^LELON "),
    Manufacturer("LIBERTY", r"^LIBERTY "),
    Manufacturer("LINDSTROM", r"^LINDSTROM "),
    Manufacturer("LINEAR TECH", r"^LINEAR TECH "),
    Manufacturer("LINEMASTER", r"^LINEMASTER "),
    Manufacturer("LINX", r"^LINX "),
    Manufacturer("LITE-ON", r"^LITE-ON "),
    Manufacturer("LITTELITE", r"^LITTELITE "),
    Manufacturer("LMI", r"^LMI "),
    Manufacturer("LSI", r"^LSI "),
    Manufacturer("LT", r"^LT "),
    Manufacturer("LUMBERG", r"^LUMBERG "),
    Manufacturer("LUMEX", r"^LUMEX "),
    Manufacturer("LZR", r"^LZR "),
    Manufacturer("M&Q", r"^M&Q "),
    Manufacturer("M/P", r"^M/P "),
    Manufacturer("MAGNECRAFT", r"^MAGNECRAFT "),
    Manufacturer("MAGNETEK", r"^MAGNETEK "),
    Manufacturer("MAGNUM", r"^MAGNUM "),
    Manufacturer("MAIDA", r"^MAIDA "),
    Manufacturer("MAJESTIC", r"^MAJESTIC "),
    Manufacturer("MARATHON", r"^MARATHON "),
    Manufacturer("MARINCO", r"^MARINCO "),
    Manufacturer("MARKEL", r"^MARKEL "),
    Manufacturer("MARLEY", r"^MARLEY "),
    Manufacturer("MATRIX", r"^MATRIX "),
    Manufacturer("MATSUSHITA", r"^MATSUSHITA "),
    Manufacturer("MAXIM", r"^MAXIM "),
    Manufacturer("MCC", r"^MCC "),
    Manufacturer("MCGILL", r"^MCGILL "),
    Manufacturer("MDI", r"^MDI "),
    Manufacturer("MEC", r"^MEC "),
    Manufacturer("MECH PROD", r"^MECH PROD "),
    Manufacturer("MECHATRONICS", r"^MECHATRONICS "),
    Manufacturer("MEPCO", r"^MEPCO "),
    Manufacturer("MER", r"^MER "),
    Manufacturer("METHODE", r"^METHODE "),
    Manufacturer("METZ", r"^METZ "),
    Manufacturer("MEYER", r"^MEYER "),
    Manufacturer("MG", r"^MG "),
    Manufacturer("MHS", r"^MHS "),
    Manufacturer("MIC", r"^MIC "),
    Manufacturer("MICREL", r"^MICREL "),
    Manufacturer("MICROCHIP", r"^MICROCHIP "),
    Manufacturer("MICROSWITCH", r"^MICROSWITCH "),
    Manufacturer("MICROTRAN", r"^MICROTRAN "),
    Manufacturer("MIDLAND ROSS", r"^MIDLAND ROSS "),
    Manufacturer("MIDWAY", r"^MIDWAY "),
    Manufacturer("MILLMAX", r"^MILLMAX "),
    Manufacturer("MIRAMAR", r"^MIRAMAR "),
    Manufacturer("MITEL", r"^MITEL "),
    Manufacturer("MIYAMA", r"^MIYAMA "),
    Manufacturer("MIYANOHM", r"^MIYANOHM "),
    Manufacturer("MMI", r"^MMI "),
    Manufacturer("MN", r"^MN "),
    Manufacturer("MOSTEK", r"^MOSTEK "),
    Manufacturer("MOTOROLA", r"^MOTOROLA "),
    Manufacturer("MOVISTAR", r"^MOVISTAR "),
    Manufacturer("MP", r"^MP "),
    Manufacturer("MPD", r"^MPD "),
    Manufacturer("MRC", r"^MRC "),
    Manufacturer("MSC", r"^MSC "),
    Manufacturer("MTX", r"^MTX "),
    Manufacturer("MULTI COMP", r"^MULTI COMP "),
    Manufacturer("MULTI COMP", r"^MULTICOMP "),
    Manufacturer("MULTICORE", r"^MULTICORE "),
    Manufacturer("MURATA", r"^MURATA "),
    Manufacturer("MVD", r"^MVD "),
    Manufacturer("NAT", r"^NAT "),
    Manufacturer("NATIONAL", r"^NATIONAL "),
    Manufacturer("NATVAR", r"^NATVAR "),
    Manufacturer("NBT", r"^NBT "),
    Manufacturer("NEC", r"^NEC "),
    Manufacturer("NEER", r"^NEER "),
    Manufacturer("NEMCO", r"^NEMCO "),
    Manufacturer("NEUTRIK", r"^NEUTRIK "),
    Manufacturer("NEXPERIA", r"^NEXPERIA "),
    Manufacturer("NIC", r"^NIC "),
    Manufacturer("NICHICON", r"^NICHICON "),
    Manufacturer("NISSEI", r"^NISSEI "),
    Manufacturer("NJR", r"^NJR "),
    Manufacturer("NKK", r"^NKK "),
    Manufacturer("NLI", r"^NLI "),
    Manufacturer("NORCOMP", r"^NORCOMP "),
    Manufacturer("NSC", r"^NSC "),
    Manufacturer("NSI", r"^NSI "),
    Manufacturer("NSPA", r"^NSPA "),
    Manufacturer("NTC", r"^NTC "),
    Manufacturer("NTT", r"^NTT "),
    Manufacturer("NXP", r"^NXP "),
    Manufacturer("NYLON NET", r"^NYLON NET "),
    Manufacturer("NZE", r"^NZE "),
    Manufacturer("OCC", r"^OCC "),
    Manufacturer("OEM", r"^OEM "),
    Manufacturer("OHMITE", r"^OHMITE "),
    Manufacturer("OHMITRAN", r"^OHMITRAN "),
    Manufacturer("OK IND", r"^OK IND "),
    Manufacturer("OKAYA", r"^OKAYA "),
    Manufacturer("OKI", r"^OKI "),
    Manufacturer("OLFLEX", r"^OLFLEX "),
    Manufacturer("OLYMPIC", r"^OLYMPIC "),
    Manufacturer("OMNI", r"^OMNI "),
    Manufacturer("OMRON", r"^OMRON "),
    Manufacturer("ON SEMI", r"^ON SEMI "),
    Manufacturer("ONS", r"^ONS "),
    Manufacturer("ON SEMI", r"^ONSEMI "),
    Manufacturer("ONSUNE", r"^ONSUNE "),
    Manufacturer("OPTEK", r"^OPTEK "),
    Manufacturer("ORS", r"^ORS "),
    Manufacturer("OSLO", r"^OSLO "),
    Manufacturer("OSRAM", r"^OSRAM "),
    Manufacturer("OTTO", r"^OTTO "),
    Manufacturer("P&B", r"^P&B "),
    Manufacturer("PAC-TEC", r"^PAC-TEC "),
    Manufacturer("PACCOM", r"^PACCOM "),
    Manufacturer("PACKARD", r"^PACKARD "),
    Manufacturer("PAC-TEC", r"^PACTEC "),
    Manufacturer("PAIGE", r"^PAIGE "),
    Manufacturer("PAKTRON", r"^PAKTRON "),
    Manufacturer("PAN PACIFIC", r"^PAN PACIFIC "),
    Manufacturer("PANASONIC", r"^PANASONIC "),
    Manufacturer("PANCON", r"^PANCON "),
    Manufacturer("PANJIT", r"^PANJIT "),
    Manufacturer("PCD", r"^PCD "),
    Manufacturer("PECOR", r"^PECOR "),
    Manufacturer("PEM", r"^PEM "),
    Manufacturer("PENN UNION", r"^PENN UNION "),
    Manufacturer("PENN-ELCOM", r"^PENN-ELCOM "),
    Manufacturer("PENTAIR", r"^PENTAIR "),
    Manufacturer("PERMA POWER", r"^PERMA POWER "),
    Manufacturer("PERMATEX", r"^PERMATEX "),
    Manufacturer("PHIHONG", r"^PHIHONG "),
    Manufacturer("PHILCO", r"^PHILCO "),
    Manufacturer("PHILIPS", r"^PHILIPS "),
    Manufacturer("PHOENIX", r"^PHOENIX "),
    Manufacturer("PHOTRONIC", r"^PHOTRONIC "),
    Manufacturer("PICKSON", r"^PICKSON "),
    Manufacturer("PIHER", r"^PIHER "),
    Manufacturer("PITTMANN", r"^PITTMANN "),
    Manufacturer("PIVOT POINT", r"^PIVOT POINT "),
    Manufacturer("PIZZATO", r"^PIZZATO "),
    Manufacturer("PLACON", r"^PLACON "),
    Manufacturer("PLANTRONICS", r"^PLANTRONICS "),
    Manufacturer("PLATO", r"^PLATO "),
    Manufacturer("PLYMOUTH", r"^PLYMOUTH "),
    Manufacturer("PM", r"^PM "),
    Manufacturer("PMI", r"^PMI "),
    Manufacturer("PMS", r"^PMS "),
    Manufacturer("POLYCASE", r"^POLYCASE "),
    Manufacturer("POMONA", r"^POMONA "),
    Manufacturer("POWER TRENDS", r"^POWER TRENDS "),
    Manufacturer("POWER-ONE", r"^POWER-ONE "),
    Manufacturer("PPE", r"^PPE "),
    Manufacturer("PQL", r"^PQL "),
    Manufacturer("PRECI CONTACT", r"^PRECI CONTACT "),
    Manufacturer("PREL", r"^PREL "),
    Manufacturer("PREM", r"^PREM "),
    Manufacturer("PREMIER METAL", r"^PREMIER METAL "),
    Manufacturer("PRI", r"^PRI "),
    Manufacturer("PRX", r"^PRX "),
    Manufacturer("PSD", r"^PSD "),
    Manufacturer("PUI", r"^PUI "),
    Manufacturer("PULS", r"^PULS "),
    Manufacturer("PULSE", r"^PULSE "),
    Manufacturer("PWR INTEGRATION", r"^PWR INTEGRATION "),
    Manufacturer("PYLE NATIONAL", r"^PYLE NATIONAL "),
    Manufacturer("QT", r"^QT "),
    Manufacturer("QTC", r"^QTC "),
    Manufacturer("QUALITEK", r"^QUALITEK "),
    Manufacturer("QUALTEK", r"^QUALTEK "),
    Manufacturer("QUAM", r"^QUAM "),
    Manufacturer("RAB", r"^RAB "),
    Manufacturer("RAF", r"^RAF "),
    Manufacturer("RAYCHEM", r"^RAYCHEM "),
    Manufacturer("RAYTHEON", r"^RAYTHEON "),
    Manufacturer("RC", r"^RC "),
    Manufacturer("RCA", r"^RCA "),
    Manufacturer("RCD", r"^RCD "),
    Manufacturer("RDI", r"^RDI "),
    Manufacturer("RECOM", r"^RECOM "),
    Manufacturer("RECTRON", r"^RECTRON "),
    Manufacturer("REDINGTON COUNTER", r"^REDINGTON COUNTER "),
    Manufacturer("RENATA", r"^RENATA "),
    Manufacturer("RF", r"^RF "),
    Manufacturer("RFE", r"^RFE "),
    Manufacturer("RGA", r"^RGA "),
    Manufacturer("RICHCO", r"^RICHCO "),
    Manufacturer("RICHEY", r"^RICHEY "),
    Manufacturer("RISTANCE", r"^RISTANCE "),
    Manufacturer("RMC", r"^RMC "),
    Manufacturer("ROBINSON NUGENT", r"^ROBINSON NUGENT "),
    Manufacturer("ROCKWELL", r"^ROCKWELL "),
    Manufacturer("ROGAN", r"^ROGAN "),
    Manufacturer("ROHM", r"^ROHM "),
    Manufacturer("ROME", r"^ROME "),
    Manufacturer("RONSON", r"^RONSON "),
    Manufacturer("ROYAL OHM", r"^ROYAL OHM "),
    Manufacturer("RSC", r"^RSC "),
    Manufacturer("RUBYCON", r"^RUBYCON "),
    Manufacturer("RUSSELL", r"^RUSSELL "),
    Manufacturer("RXD", r"^RXD "),
    Manufacturer("S&EI", r"^S&EI "),
    Manufacturer("S/E", r"^S/E "),
    Manufacturer("SAE", r"^SAE "),
    Manufacturer("SAGE", r"^SAGE "),
    Manufacturer("SAHA", r"^SAHA "),
    Manufacturer("SAMSUNG", r"^SAMSUNG "),
    Manufacturer("SAMTEC", r"^SAMTEC "),
    Manufacturer("SAMWHA", r"^SAMWHA "),
    Manufacturer("SANDAN", r"^SANDAN "),
    Manufacturer("SANGAMO", r"^SANGAMO "),
    Manufacturer("SANNOHM", r"^SANNOHM "),
    Manufacturer("SARGENT", r"^SARGENT "),
    Manufacturer("SARKES TARZIAN", r"^SARKES TARZIAN "),
    Manufacturer("SAS", r"^SAS "),
    Manufacturer("SBMP", r"^SBMP "),
    Manufacturer("SC1", r"^SC1 "),
    Manufacturer("SCANBE", r"^SCANBE "),
    Manufacturer("SCC", r"^SCC "),
    Manufacturer("SCHAFFNER", r"^SCHAFFNER "),
    Manufacturer("SCHILLER", r"^SCHILLER "),
    Manufacturer("SCHLEMMER", r"^SCHLEMMER "),
    Manufacturer("SCHRACK", r"^SCHRACK "),
    Manufacturer("SCHROFF", r"^SCHROFF "),
    Manufacturer("SCHURTER", r"^SCHURTER "),
    Manufacturer("SCIAKY", r"^SCIAKY "),
    Manufacturer("SEC", r"^SEC "),
    Manufacturer("SEDECAL", r"^SEDECAL "),
    Manufacturer("SEI", r"^SEI "),
    Manufacturer("SEMCOR", r"^SEMCOR "),
    Manufacturer("SEMICON", r"^SEMICON "),
    Manufacturer("SEMICON", r"^SEMICONDUCTORS "),
    Manufacturer("SEMITRON", r"^SEMITRON "),
    Manufacturer("SENTROL", r"^SENTROL "),
    Manufacturer("SES", r"^SES "),
    Manufacturer("SET", r"^SET "),
    Manufacturer("SGS", r"^SGS "),
    Manufacturer("SHARP", r"^SHARP "),
    Manufacturer("SHATTUCK", r"^SHATTUCK "),
    Manufacturer("SHELLY", r"^SHELLY "),
    Manufacturer("SHENZHEN", r"^SHENZHEN "),
    Manufacturer("SHIGMA", r"^SHIGMA "),
    Manufacturer("SI", r"^SI "),
    Manufacturer("SIEMENS", r"^SIEMENS "),
    Manufacturer("SIGMA", r"^SIGMA "),
    Manufacturer("SIGNAL TRANS", r"^SIGNAL TRANS "),
    Manufacturer("SIGNETICS", r"^SIGNETICS "),
    Manufacturer("SILICON DIODE", r"^SILICON DIODE "),
    Manufacturer("SILICONIX", r"^SILICONIX "),
    Manufacturer("SILONEX", r"^SILONEX "),
    Manufacturer("SILTEK", r"^SILTEK "),
    Manufacturer("SIMPSON", r"^SIMPSON "),
    Manufacturer("SINGATRON", r"^SINGATRON "),
    Manufacturer("SIPEX", r"^SIPEX "),
    Manufacturer("SJK", r"^SJK "),
    Manufacturer("SLICE", r"^SLICE "),
    Manufacturer("SMC", r"^SMC "),
    Manufacturer("SOCKETS PLUS", r"^SOCKETS PLUS "),
    Manufacturer("SOLA", r"^SOLA "),
    Manufacturer("SOLITRON", r"^SOLITRON "),
    Manufacturer("SOSHIN", r"^SOSHIN "),
    Manufacturer("SOURIAU", r"^SOURIAU "),
    Manufacturer("SOUTHWIRE", r"^SOUTHWIRE "),
    Manufacturer("SOVTEK", r"^SOVTEK "),
    Manufacturer("SPC TECH", r"^SPC TECH "),
    Manufacturer("SPECTROL", r"^SPECTROL "),
    Manufacturer("SPECTRONICS", r"^SPECTRONICS "),
    Manufacturer("SPI", r"^SPI "),
    Manufacturer("SPPERIOR ESSEX", r"^SPPERIOR ESSEX "),
    Manufacturer("SPRAGUE", r"^SPRAGUE "),
    Manufacturer("SPRAYON", r"^SPRAYON "),
    Manufacturer("SQUARE D", r"^SQUARE D "),
    Manufacturer("SRC", r"^SRC "),
    Manufacturer("SS", r"^SS "),
    Manufacturer("SSC", r"^SSC "),
    Manufacturer("SSI", r"^SSI "),
    Manufacturer("SSS", r"^SSS "),
    Manufacturer("ST MICRO", r"^ST MICRO "),
    Manufacturer("STACKPOLE", r"^STACKPOLE "),
    Manufacturer("STAHLIN", r"^STAHLIN "),
    Manufacturer("STANLEY", r"^STANLEY "),
    Manufacturer("STAUFF", r"^STAUFF "),
    Manufacturer("STC", r"^STC "),
    Manufacturer("STEINEL", r"^STEINEL "),
    Manufacturer("STEWARD", r"^STEWARD "),
    Manufacturer("STEWART", r"^STEWART "),
    Manufacturer("STIMPSON", r"^STIMPSON "),
    Manufacturer("STL", r"^STL "),
    Manufacturer("STONE CITY", r"^STONE CITY "),
    Manufacturer("STP", r"^STP "),
    Manufacturer("SULLINS", r"^SULLINS "),
    Manufacturer("SUMITOMO", r"^SUMITOMO "),
    Manufacturer("SUN EAST", r"^SUN EAST "),
    Manufacturer("SUPER TEX", r"^SUPER TEX "),
    Manufacturer("SUPERIOR FLUX", r"^SUPERIOR FLUX "),
    Manufacturer("SUPERTEX", r"^SUPERTEX "),
    Manufacturer("SUPREME", r"^SUPREME "),
    Manufacturer("SURFACE MOUNT", r"^SURFACE MOUNT "),
    Manufacturer("SURGE", r"^SURGE "),
    Manufacturer("SUSCO", r"^SUSCO "),
    Manufacturer("SW", r"^SW "),
    Manufacturer("SWC", r"^SWC "),
    Manufacturer("SWITCHCRAFT", r"^SWITCHCRAFT "),
    Manufacturer("SYLVANIA", r"^SYLVANIA "),
    Manufacturer("SYMBOL", r"^SYMBOL "),
    Manufacturer("SYTRON", r"^SYTRON "),
    Manufacturer("TAD", r"^TAD "),
    Manufacturer("TAIKO", r"^TAIKO "),
    Manufacturer("TAIYAO", r"^TAIYAO "),
    Manufacturer("TAIYO YUDEN", r"^TAIYO YUDEN "),
    Manufacturer("TAMURA", r"^TAMURA "),
    Manufacturer("TANSTAAFL", r"^TANSTAAFL "),
    Manufacturer("TAPE IT", r"^TAPE IT "),
    Manufacturer("TAPPAN", r"^TAPPAN "),
    Manufacturer("TAYTRONICS", r"^TAYTRONICS "),
    Manufacturer("TDK", r"^TDK "),
    Manufacturer("TE", r"^TE "),
    Manufacturer("TEC", r"^TEC "),
    Manufacturer("TECATE", r"^TECATE "),
    Manufacturer("TECCOR", r"^TECCOR "),
    Manufacturer("TECHFLEX", r"^TECHFLEX "),
    Manufacturer("TECOR", r"^TECOR "),
    Manufacturer("TEKNATIONAL", r"^TEKNATIONAL "),
    Manufacturer("TELEDYNE", r"^TELEDYNE "),
    Manufacturer("TELEFUNKEN", r"^TELEFUNKEN "),
    Manufacturer("TELELONG", r"^TELELONG "),
    Manufacturer("TELEMECANIQUE", r"^TELEMECANIQUE "),
    Manufacturer("TEMIC", r"^TEMIC "),
    Manufacturer("TF", r"^TF "),
    Manufacturer("THERMALLOY", r"^THERMALLOY "),
    Manufacturer("THERMODISC", r"^THERMODISC "),
    Manufacturer("THERMOMETRICS", r"^THERMOMETRICS "),
    Manufacturer("THERMSHIELD", r"^THERMSHIELD "),
    Manufacturer("THOMPSON", r"^THOMPSON "),
    Manufacturer("THOMSON", r"^THOMSON "),
    Manufacturer("THORDARSON", r"^THORDARSON "),
    Manufacturer("TI", r"^TI "),
    Manufacturer("TIME", r"^TIME "),
    Manufacturer("TIS", r"^TIS "),
    Manufacturer("TOKAI RIKA", r"^TOKAI RIKA "),
    Manufacturer("TOKO", r"^TOKO "),
    Manufacturer("TOL", r"^TOL "),
    Manufacturer("TOP OHM", r"^TOPOHM "),
    Manufacturer("TOSHIBA", r"^TOSHIBA "),
    Manufacturer("TRANSFORMERS INC", r"^TRANSFORMERS INC "),
    Manufacturer("TRANSISTOR", r"^TRANSISTOR "),
    Manufacturer("TRANSITRON", r"^TRANSITRON "),
    Manufacturer("TRANSOHM", r"^TRANSOHM "),
    Manufacturer("TRIAD", r"^TRIAD "),
    Manufacturer("TRIANGLE", r"^TRIANGLE "),
    Manufacturer("TRIDON", r"^TRIDON "),
    Manufacturer("TRIGON", r"^TRIGON "),
    Manufacturer("TRIPLEX", r"^TRIPLEX "),
    Manufacturer("TRIPP-LITE", r"^TRIPP-LITE "),
    Manufacturer("TRW", r"^TRW "),
    Manufacturer("TS", r"^TS "),
    Manufacturer("TSC", r"^TSC "),
    Manufacturer("TSU", r"^TSU "),
    Manufacturer("TUNG-SOL", r"^TUNG-SOL "),
    Manufacturer("TURCK", r"^TURCK "),
    Manufacturer("TWC", r"^TWC "),
    Manufacturer("TXT", r"^TXT "),
    Manufacturer("TYCO", r"^TYCO "),
    Manufacturer("TYTON", r"^TYTON "),
    Manufacturer("UCC", r"^UCC "),
    Manufacturer("UFC", r"^UFC "),
    Manufacturer("ULTRA", r"^ULTRA "),
    Manufacturer("UMC", r"^UMC "),
    Manufacturer("UMPCO", r"^UMPCO "),
    Manufacturer("UNGAR", r"^UNGAR "),
    Manufacturer("UNITROBE", r"^UNITROBE "),
    Manufacturer("UNITRODE", r"^UNITRODE "),
    Manufacturer("UNIVERSAL", r"^UNIVERSAL "),
    Manufacturer("UNIZON", r"^UNIZON "),
    Manufacturer("UPI", r"^UPI "),
    Manufacturer("USN", r"^USN "),
    Manufacturer("UTC", r"^UTC "),
    Manufacturer("UWC", r"^UWC "),
    Manufacturer("VABSCO", r"^VABSCO "),
    Manufacturer("VACO", r"^VACO "),
    Manufacturer("VALCONN", r"^VALCONN "),
    Manufacturer("VARO", r"^VARO "),
    Manufacturer("VARTA", r"^VARTA "),
    Manufacturer("VCC", r"^VCC "),
    Manufacturer("VECTOR", r"^VECTOR "),
    Manufacturer("VELLEMAN", r"^VELLEMAN "),
    Manufacturer("VELLEMAN", r"^VELLMAN "),
    Manufacturer("VIKING", r"^VIKING "),
    Manufacturer("VIMEX", r"^VIMEX "),
    Manufacturer("VINNIC", r"^VINNIC "),
    Manufacturer("VIP", r"^VIP "),
    Manufacturer("VISHAY", r"^VISHAY "),
    Manufacturer("VORTEX", r"^VORTEX "),
    Manufacturer("VRN", r"^VRN "),
    Manufacturer("VTE", r"^VTE "),
    Manufacturer("VTL", r"^VTL "),
    Manufacturer("W/E", r"^W/E "),
    Manufacturer("WABER", r"^WABER "),
    Manufacturer("WAF", r"^WAF "),
    Manufacturer("WAFER SEMI", r"^WAFER SEMI "),
    Manufacturer("WAGNER", r"^WAGNER "),
    Manufacturer("WAGO", r"^WAGO "),
    Manufacturer("WAKEFIELD", r"^WAKEFIELD "),
    Manufacturer("WALBERN DEVICES", r"^WALBERN DEVICES "),
    Manufacturer("WATTMAN", r"^WATTMAN "),
    Manufacturer("WEBBER", r"^WEBBER "),
    Manufacturer("WEIDMULLER", r"^WEIDMULLER "),
    Manufacturer("WELLER", r"^WELLER "),
    Manufacturer("WEST CAP", r"^WEST CAP "),
    Manufacturer("WEST CAP", r"^WEST-CAP "),
    Manufacturer("WESTCODE", r"^WESTCODE "),
    Manufacturer("WESTINGHOUSE", r"^WESTINGHOUSE "),
    Manufacturer("WESTON", r"^WESTON "),
    Manufacturer("WHITAKER", r"^WHITAKER "),
    Manufacturer("WHITE-RODGERS", r"^WHITE-RODGERS "),
    Manufacturer("WHITNEY BLAKE", r"^WHITNEY BLAKE "),
    Manufacturer("WIELAND", r"^WIELAND "),
    Manufacturer("WILCO", r"^WILCO "),
    Manufacturer("WILL", r"^WILL "),
    Manufacturer("WIMA", r"^WIMA "),
    Manufacturer("WINCHESTER", r"^WINCHESTER "),
    Manufacturer("WIREMOLD", r"^WIREMOLD "),
    Manufacturer("WISLL", r"^WISLL "),
    Manufacturer("WIX", r"^WIX "),
    Manufacturer("WOODS", r"^WOODS "),
    Manufacturer("WOODWARD", r"^WOODWARD "),
    Manufacturer("WORKMAN", r"^WORKMAN "),
    Manufacturer("WPI", r"^WPI "),
    Manufacturer("WSI", r"^WSI "),
    Manufacturer("WX", r"^WX "),
    Manufacturer("WXP", r"^WXP "),
    Manufacturer("X-ACTO", r"^X-ACTO "),
    Manufacturer("XCELITE", r"^XCELITE "),
    Manufacturer("XICON", r"^XICON "),
    Manufacturer("XICOR", r"^XICOR "),
    Manufacturer("XR", r"^XR "),
    Manufacturer("YAGEO", r"^YAGEO "),
    Manufacturer("YAGGO", r"^YAGGO "),
    Manufacturer("YAZAKI", r"^YAZAKI "),
    Manufacturer("YINJI", r"^YINJI "),
    Manufacturer("ZAMCO", r"^ZAMCO "),
    Manufacturer("ZEBRA", r"^ZEBRA "),
    Manufacturer("ZENER", r"^ZENER "),
    Manufacturer("ZERO", r"^ZERO "),
    Manufacturer("ZETATRONIC", r"^ZETATRONIC "),
    Manufacturer("ZETEX", r"^ZETEX "),
    Manufacturer("ZEUS", r"^ZEUS "),
    Manufacturer("ZF", r"^ZF "),
    Manufacturer("ZIERICK", r"^ZIERICK "),
    Manufacturer("ZILOG", r"^ZILOG "),
    Manufacturer("ZING EAR", r"^ZING EAR "),
    Manufacturer("ZORO", r"^ZORO "),
    Manufacturer("ZX", r"^ZX "),
    Manufacturer("ZYTREX", r"^ZYTREX "),
]
